/**
 * Build-time fetch: pulls the menu content from Sanity's isolated `menu`
 * dataset (project 12plpqm0 — the SAME project as sunday-website, but a
 * dataset created specifically for this site, with no content overlap with
 * `production`) and writes a plain generated JS file the static site loads.
 *
 * Runs at Vercel build time (`npm run build`), never in the browser, so the
 * read token never reaches client-side code.
 *
 * Dataset is hardcoded (never env-driven) so this can never be pointed at
 * `production` by a stray env var. See sunday-studio's migration script for
 * the matching isolation rationale.
 */
import { createClient } from '@sanity/client'
import imageUrlBuilder from '@sanity/image-url'
import { writeFileSync } from 'node:fs'

const PROJECT_ID = '12plpqm0'
const DATASET = 'menu'

const token = process.env.SANITY_MENU_READ_TOKEN
if (!token) {
  console.error('ERROR: SANITY_MENU_READ_TOKEN is not set.')
  process.exit(1)
}

const client = createClient({
  projectId: PROJECT_ID,
  dataset: DATASET,
  apiVersion: '2021-10-21',
  token,
  // Build-time script: always read fresh data, never the API CDN cache —
  // a stale cache here would silently ship outdated menu content.
  useCdn: false,
})

if (client.config().dataset !== DATASET) {
  throw new Error(
    `Refusing to build: client dataset is "${client.config().dataset}", expected "${DATASET}".`
  )
}

const urlFor = (source) => imageUrlBuilder(client).image(source)

const QUERY = `*[_type == "visualMenuSection"] | order(displayOrder asc){
  _id, key, tab, title, displayOrder,
  "items": *[_type == "visualMenuItem" && references(^._id)] | order(displayOrder asc){
    _id, name, description, tag, displayOrder, image
  }
}`

const LABELS_QUERY = `*[_id == "visualMenuUiLabels"][0]{foodTab, drinksTab, ingredients, itemsCount, byoTitle, byoSupport, byoCta}`

// Adding a language = add its code here (and to the schema + front-end LOCALES).
const LOCALES = ['en', 'zh', 'ru', 'id', 'ja', 'ko']

// English defaults keep the site building even before the labels singleton
// exists in the dataset (and double as the en fallback shape).
const DEFAULT_LABELS = {
  foodTab: { en: 'Food' },
  drinksTab: { en: 'Drinks' },
  ingredients: { en: 'Ingredients' },
  itemsCount: { en: 'items' },
  // BYO end-of-menu card. byoTitle/byoSupport hold literal newlines — the
  // front-end renders them with `white-space: pre-line`, so where a line
  // breaks is a per-language content decision, not markup.
  byoTitle: { en: 'Build Your Own\n(with macros)' },
  byoSupport: {
    en:
      'Pick your protein, bases, sides, vegetables and more. ' +
      'Macros, weight and calories on every ingredient. ' +
      'Build your plate in our macro calculator.',
  },
  byoCta: { en: 'View BYO Menu' },
}

// {en: ..., zh: ..., ru: ...} with null for missing locales; en falls back
// to the hardcoded default so the site never renders blank.
const shapeLocale = (field, fallback = {}) =>
  Object.fromEntries(
    LOCALES.map((loc) => [
      loc,
      field?.[loc] || (loc === 'en' ? fallback.en || '' : null),
    ])
  )

async function main() {
  const [sections, labelsDoc] = await Promise.all([
    client.fetch(QUERY),
    client.fetch(LABELS_QUERY),
  ])

  const labels = Object.fromEntries(
    Object.entries(DEFAULT_LABELS).map(([key, fallback]) => [
      key,
      shapeLocale(labelsDoc?.[key], fallback),
    ])
  )

  const shapeItem = (item) => ({
    name: shapeLocale(item.name),
    desc: item.description ? shapeLocale(item.description) : null,
    tag: item.tag ? shapeLocale(item.tag) : null,
    img: item.image
      ? urlFor(item.image).width(800).fit('max').auto('format').quality(80).url()
      : null,
  })

  const shapeSection = (s) => ({
    key: s.key,
    title: shapeLocale(s.title),
    items: (s.items || []).map(shapeItem),
  })

  const food = sections.filter((s) => s.tab === 'food').map(shapeSection)
  const drinks = sections.filter((s) => s.tab === 'drinks').map(shapeSection)

  const itemCount = [...food, ...drinks].reduce((n, s) => n + s.items.length, 0)
  console.log(
    `Fetched ${sections.length} section(s), ${itemCount} item(s) from dataset "${DATASET}".`
  )

  const out = `// AUTO-GENERATED by scripts/build-menu.mjs — do not edit by hand.\n` +
    `window.MENU_DATA = ${JSON.stringify({ food, drinks, labels }, null, 2)};\n`
  writeFileSync(new URL('../menu-data.generated.js', import.meta.url), out)
  console.log('Wrote menu-data.generated.js')
}

main().catch((e) => {
  console.error('BUILD FAILED:', e.message)
  process.exit(1)
})
